dashing:
  image: mintel/smashing
  env_file:
    - .env
  volumes:
    - ./dashboards:/dashboards
    - ./jobs:/jobs
    - ./assets:/assets
    - ./widgets:/widgets
    - ./config:/config
  ports:
    - "8080:3030"
